version: '3.8'

services:

  app:
    build: .
    container_name: backend
    restart: "no"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: postgres  # имя сервиса базы данных
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    restart: "no"  # избавляемся от автоматической перезагрузки
    ports:
      - "5432:5432"
    environment:
      # Superuser username/password
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"
  pgadmin:
      image: dpage/pgadmin4:latest
      restart: "no"
      ports:
        - "8080:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      volumes:
        - "01-simple-alchemy-pgadmin:/var/lib/pgadmin"
      depends_on:
        - postgres

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres: