"""Delete fuckin fields

Revision ID: 1f4c2e008635
Revises: b031c96d84b9
Create Date: 2025-03-23 03:45:23.820257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4c2e008635'
down_revision: Union[str, None] = 'b031c96d84b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'old_price')
    op.drop_column('products', 'price')
    op.drop_column('products', 'discount')
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('old_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
