"""Add product fields

Revision ID: 6b090964bed9
Revises: bc9c29053b77
Create Date: 2025-04-07 23:35:17.799420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b090964bed9'
down_revision: Union[str, None] = 'bc9c29053b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fat_content', sa.String(), nullable=True))
    op.add_column('products', sa.Column('volume', sa.String(), nullable=True))
    op.add_column('products', sa.Column('compound', sa.String(), nullable=True))
    op.add_column('products', sa.Column('energy_value', sa.String(), nullable=True))
    op.add_column('products', sa.Column('protein', sa.String(), nullable=True))
    op.add_column('products', sa.Column('fats', sa.String(), nullable=True))
    op.add_column('products', sa.Column('carbs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'carbs')
    op.drop_column('products', 'fats')
    op.drop_column('products', 'protein')
    op.drop_column('products', 'energy_value')
    op.drop_column('products', 'compound')
    op.drop_column('products', 'volume')
    op.drop_column('products', 'fat_content')
    # ### end Alembic commands ###
